<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <AssemblyName>PvZGE-WebServer</AssemblyName>
    <RootNamespace>PvzgeWeb</RootNamespace>
    <Product>PvZ2 Gardendless 本地 Web 服务器</Product>
    <Version>1.0.0</Version>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DebugType>none</DebugType>
  </PropertyGroup>

</Project>
